name: Build (Dev)

on:
  # Remember to change this to only create new releases after PRs or something more significant than a push.
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: macos-latest
    steps: 
      - name: Setup NASM                      # Load required build tool nasm
        uses: ilammy/setup-nasm@v1
      - name: Checkout                        # Checkout repo before doing the rest
        uses: actions/checkout@master
      - name: Spin up build cache             # Init cache to persist previous build
        uses: mikehardy/buildcache-action@v1
      - name: Clean up old binaries           # Clean up previous build trash
        run: make clean
      - name: Build new binary                # Make macOS binary (.dylib)
        run: make
      - name: Create release                  # Create a GitHub release for new build
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          bodyFile: 'RELEASE.md'
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release artifact         # Upload built binary to created release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mupen64plus_next_libretro.dylib
          asset_name: mupen64plus_next_libretro.dylib
          asset_content_type: application/x-mach-binary
