name: Build (Dev)

on:
  # Remember to change this to only create new releases after PRs or something more significant than a push.
  push:
    tags:
      - '*'
#     branches: [ develop ]
#   pull_request:
#     branches: [ develop ]
#   workflow_dispatch:

jobs:
  build:
    name: Build (Dev)
    runs-on: macos-latest
    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@master
    # Cache output files in dist directory
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: test/dist/cache
        key: ${{ runner.os }}-makefile-${{ github.sha }}-${{ hashFiles('**/makefile') }}
        restore-keys: |
          ${{ runner.os }}-makefile-
    # This workflow change updated time of files was not changed.
    # You can control behavior by setting reference, or commit id.
    # See below more infomation.
    - name: Change updated time
      uses: flat35hd99/cache-make@v1.0.0
#     - uses: mikehardy/buildcache-action@v1
#     - name: Clean up
#       run: make clean
    - name: Run make
      run: make
#   compress:
#     needs: build
#     name: Compress Build Results
#     runs-on: macos-latest
#     steps:
#     - name: Zip compiled binary
#       uses: thedoctor0/zip-release@master
#       with:
#         type: 'zip'
# #         directory: './dist'
#         path: 'mupen64plus_next_libretro.dylib'
#         filename: 'mupen64plus-next-dev.zip'
#         exclusions: '*.git* .editorconfig'
#   release:
#     needs: compress
#     name: Publish release
#     runs-on: macos-latest
#     steps:
#       - name: Upload Release
#         uses: ncipollo/release-action@v1
#         with:
#           tag: "v0.4.0-dev"
#           commit: ${{ github.sha }}
# #           name: "Development Release"
#           body: "Testing release CI workflow"
#           artifacts: "mupen64plus-next-dev.zip"
#           token: ${{ secrets.GITHUB_TOKEN }}
