name: Build (Dev)

on:
  # Remember to change this to only create new releases after PRs or something more significant than a push.
  push:
    tags:
      - '*'
#    branches: [ develop ]
#   pull_request:
#     branches: [ develop ]
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: macos-latest
    steps: 
      - name: Setup NASM
        uses: ilammy/setup-nasm@v1
      - name: Checkout
        uses: actions/checkout@master
      - name: Spin up build cache
        uses: mikehardy/buildcache-action@v1
      - name: Clean up old binaries
        run: make clean
      - name: Build new binaries
        run: make
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: 'Testing release CI'
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mupen64plus_next_libretro.dylib
          asset_name: mupen64plus_next_libretro.dylib
          asset_content_type: application/x-mach-binary
