name: Makefile CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build for macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    #- name: configure
    #  run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
