name: Makefile CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build for macOS
    runs-on: macos-latest

    steps:
    - uses: ilammy/setup-nasm@v1
    - uses: actions/checkout@v2
    - uses: mikehardy/buildcache-action@v1
    
    #- name: configure
    #  run: ./configure
    
    - name: Clean up old binaries
      run: make clean
      
    - name: Run make
      run: make
      
    #- name: Run check
    #  run: make check
      
    #- name: Run distcheck
    #  run: make distcheck
