# This is a basic workflow to help you get started with Actions

name: Create Release 

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Build (Dev)"]
    types: [completed]
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  on-success:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v0.4.0-dev"
          commit: ${{ github.sha }}
          name: "Development Release"
          body: "Testing release CI workflow"
          artifacts: "./dist/mupen64plus-next-dev.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
